import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#47585c] text-[#c8d5bb] relative`}
      >
        {children}
        <svg
          aria-hidden
          className="absolute inset-0 pointer-events-none opacity-30"
          width="100%"
          height="100%"
        >
          <defs>
            <filter id="noise">
              <feTurbulence
                type="fractalNoise"
                result="turbulence"
                baseFrequency="0.8"
                numOctaves="4"
                seed="10"
                stitchTiles="stitch"
              />
            </filter>
          </defs>
          <rect width="100%" height="100%" filter="url(#noise)" />
        </svg>
      </body>
    </html>
  );
}
